### ISSUE TITLE
PUBG mobile 

### ISSUE THREAD

**Issue by onlyanonym** [cool-dev-code/Gameloop-iPad-view-Keymapping#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop** (please complete the following information):
 - OS: [e.g. Windows 10/11]
 - Edition [e.g. Home/Pro]
 - Version [e.g. 22H2]
 - Architecture [e.g. 32/64 bit]
 - Gameloop Version [e.g. 4.1.128.90]
 - PUBG Mobile Version [e.g. 2.7]

**Additional context**

**Comment by cool-dev-code** [comment]
Incomplete information.
What is this ?

**Comment by onlyanonym** [comment]
I have no idea.

**Comment by cool-dev-code** [comment]
Then why did you sent bro

**Comment by cool-dev-code** [comment]
Closing this issue
