### ISSUE TITLE
Shift Button not working

### ISSUE THREAD

**Issue by dev-plus-creator** [cool-dev-code/Gameloop-iPad-view-Keymapping#4]
### To Reproduce
- Steps to reproduce the behaviour:
1. In `Match`
2. While `Driving`
3. Press `Shift` Button
4. `Car Boost` Not working

### Expected behaviour
- Should boost Car

### Screenshots
- Not applicable

### Please give the following info:
 - Windows: `11` [e.g. 10/11]
 - Windows Version: `24H2` [e.g. 24H2]
 - Gameloop Architecture: `64` [e.g. 32/64 bit]
 - Gameloop Version: `4.1.135.90` [e.g. 4.1.135.90]
 - PUBG Mobile Version: `3.5` [e.g. 3.5]

### Additional context
Not applicable

**Comment by cool-dev-code** [comment]
- Already Fixed Check Latest Pre-Release
- Closing this issue
